name: guftagu_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0-alpha25-rc+25

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  flutter_image_compress: ^2.4.0

  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  flutter_keyboard_visibility: ^6.0.0
  audio_waveforms: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  rename_app: ^1.6.2
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - assets/images/model/
    - assets/images/onboarding/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#000000"
  remove_alpha_ios: true
  background_color_ios: "#000000"
