version: 2.1

executors:
  flutter_executor:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.27.0

jobs:
  build_release_apk:
    executor: flutter_executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Build Android Release APK
          command: |
            flutter build apk --release

            TAG_NAME=${CIRCLE_TAG:-"no-tag"}
            TIMESTAMP=$(date +%F_%H-%M)
            DYNAMIC_ARTIFACT_FILENAME="app-release_${TAG_NAME}-${TIMESTAMP}"
            echo "Generated artifact filename: $DYNAMIC_ARTIFACT_FILENAME"

            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/$DYNAMIC_ARTIFACT_FILENAME.apk

            echo "export DYNAMIC_ARTIFACT_FILENAME=$DYNAMIC_ARTIFACT_FILENAME" >> $BASH_ENV
      - store_artifacts:
          path: build/app/outputs/flutter-apk
          destination: apks

workflows:
  build_on_main:
    when: << pipeline.git.branch >> == "alpha"
    jobs:
      - build_release_apk
