version: 2.1

jobs:
  build_release_apk:
    docker:
      - image: cimg/flutter:3.27.0
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            flutter pub get

      - run:
          name: Build Release APK (unsigned in CI)
          command: |
            flutter build apk --release

            # Generate a timestamp
            TIMESTAMP=$(date +%F_%H-%M)
            BRANCH_NAME=${CIRCLE_BRANCH:-unknown}

            # Construct the filename
            ARTIFACT_NAME="app-release_${BRANCH_NAME}-${TIMESTAMP}.apk"

            # Rename the APK
            mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/$ARTIFACT_NAME

            # Save filename for next steps
            echo "export ARTIFACT_NAME=$ARTIFACT_NAME" >> $BASH_ENV

      - store_artifacts:
          path: build/app/outputs/flutter-apk
          destination: apk-artifacts

workflows:
  build_on_main:
    when:
      condition:
        equal: [ alpha, << pipeline.git.branch >> ]
    jobs:
      - build_release_apk
