version: 2.1

defaults: &flutter_docker
  docker:
    - image: ghcr.io/cirruslabs/flutter:3.27.0

android_docker: &android_docker
  docker:
    - image: cimg/android:2024.09

jobs:
  create_pr_alpha_to_main:
    <<: *flutter_docker
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            sudo apt update && sudo apt install -y gh
      - run:
          name: Create PR from alpha to main
          command: |
             gh pr create --base main --head harsh --title "Automated PR from harsh to main" --body "Auto-created by CircleCI"

  create_pr_main_to_tests:
    <<: *flutter_docker
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            sudo apt update && sudo apt install -y gh
      - run:
          name: Create PR from main to tests
          command: |
             gh pr create --base tests --head main --title "Automated PR from main to tests" --body "Auto-created by CircleCI"

  build_release_android_job:
    <<: *android_docker
    steps:
      - checkout
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

workflows:
  pr_automation_workflow:
    jobs:
      - create_pr_alpha_to_main:
          filters:
            branches:
              only: alpha
      - create_pr_main_to_tests:
          filters:
            branches:
              only: main

  build_on_main_workflow:
    jobs:
      - build_release_android_job:
          filters:
            branches:
              only: tests

