version: 2.1

executors:
  flutter_executor:
    docker: 
      - image: ghcr.io/cirruslabs/flutter:latest



jobs:
  build_android_debug_apk:
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.27.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Build Android Debug APK
          command: |
            flutter build apk --debug
            TIMESTAMP=$(date +%F_%H-%M)
            DYNAMIC_FILENAME="app-debug-${TIMESTAMP}.apk"
            mv build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/$DYNAMIC_FILENAME
            echo "export DYNAMIC_FILENAME=$DYNAMIC_FILENAME" >> $BASH_ENV
      - store_artifacts:
          path: build/app/outputs/flutter-apk
          destination: apk


workflows:
  build_on_main:
    when: << pipeline.git.branch >> == "alpha"
    jobs:
      - build_android_debug_apk
      
