// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9M47zB1Tyx1VjSGT_gVtlyK0a345HN2c',
    appId: '1:19508565659:android:0d151bac5f36ed0b37d83e',
    messagingSenderId: '19508565659',
    projectId: 'guftagu-dev',
    storageBucket: 'guftagu-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYGBYoUC0c-RfOEYB3eV0vLYXexzMWVE',
    appId: '1:19508565659:ios:0fee6e27d7c6335937d83e',
    messagingSenderId: '19508565659',
    projectId: 'guftagu-dev',
    storageBucket: 'guftagu-dev.firebasestorage.app',
    androidClientId: '19508565659-2c7co4a8fdj92t49dl2amf6knio41pm1.apps.googleusercontent.com',
    iosClientId: '19508565659-ochoi50fgcs5i5j0trkcu5q21m6vu5eh.apps.googleusercontent.com',
    iosBundleId: 'com.guftagu.app',
  );

}